plugins:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Max: 30
  Exclude:
    - "test/**/*"
    - "*.gemspec"

Metrics/AbcSize:
  Max: 20

Metrics/ParameterLists:
  CountKeywordArgs: false

Metrics/MethodLength:
  Max: 15

Style/MultilineBlockChain:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 10

Minitest/MultipleAssertions:
  Max: 11

Metrics/ClassLength:
  Max: 155